<a href="https://colab.research.google.com/github/amitsingh6261/Machine_learning/blob/main/col_transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
import pandas as pd

df = pd.DataFrame({
    "Age": [21, 25, 30, 28, 35, 22, 40, 27, 32, 24],
    "Salary": [25000, 35000, 50000, 45000, 60000, 28000, 75000, 40000, 55000, 30000],
    "City": ["Indore", "Delhi", "Mumbai", "Bhopal", "Indore",
             "Delhi", "Mumbai", "Indore", "Bhopal", "Delhi"],
    "Gender": ["Male", "Female", "Male", "Female", "Male",
               "Female", "Male", "Male", "Female", "Female"],
    "Experience": [1, 2, 5, 4, 8, 1, 10, 3, 6, 2]
})

print(df)

   Age  Salary    City  Gender  Experience
0   21   25000  Indore    Male           1
1   25   35000   Delhi  Female           2
2   30   50000  Mumbai    Male           5
3   28   45000  Bhopal  Female           4
4   35   60000  Indore    Male           8
5   22   28000   Delhi  Female           1
6   40   75000  Mumbai    Male          10
7   27   40000  Indore    Male           3
8   32   55000  Bhopal  Female           6
9   24   30000   Delhi  Female           2

In [80]:
from sklearn.model_selection import train_test_split

In [81]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [82]:
x_train

   Age  Salary
0   21   25000
8   32   55000
4   35   60000
3   28   45000
9   24   30000
5   22   28000
7   27   40000
1   25   35000

In [83]:
x_test

   Age  Salary
6   40   75000
2   30   50000

In [84]:
X = df

In [85]:
x_train, x_test = train_test_split(
    X,
    test_size=0.2,
    random_state=42
)

In [86]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [87]:


transformers = ColumnTransformer(
    transformers=[
        ('tnf1', StandardScaler(), ['Age', 'Salary'])
    ],
    remainder='passthrough'
)

x_train_transformed = transformers.fit_transform(x_train)

print(x_train_transformed)

[[-1.0447398365428537 -0.9993396367282236 'Delhi' 'Female' 1]
 [-1.2086205952162425 -1.1852632900730093 'Indore' 'Male' 1]
 [-0.22533604317590963 -0.25564502334908046 'Indore' 'Male' 3]
 [0.26630623284425686 0.3641004878002055 'Mumbai' 'Male' 5]
 [-0.7169783191960761 -0.8753905344983663 'Delhi' 'Female' 2]
 [1.085710026211201 0.9838459989494914 'Indore' 'Male' 8]
 [-0.06145528450252081 0.05422773222556252 'Bhopal' 'Female' 4]
 [1.9051138195781452 1.9134642656734204 'Mumbai' 'Male' 10]]

In [88]:
x_train_transformed = transformers.fit_transform(x_train)

In [89]:
x_test_transformed = transformers.transform(x_test)

In [90]:
print("Original X_train:")
print(x_train)

Original X_train:
   Age  Salary    City  Gender  Experience
5   22   28000   Delhi  Female           1
0   21   25000  Indore    Male           1
7   27   40000  Indore    Male           3
2   30   50000  Mumbai    Male           5
9   24   30000   Delhi  Female           2
4   35   60000  Indore    Male           8
3   28   45000  Bhopal  Female           4
6   40   75000  Mumbai    Male          10

In [91]:
print("Transformed X_train:")
print(x_train_transformed)

Transformed X_train:
[[-1.0447398365428537 -0.9993396367282236 'Delhi' 'Female' 1]
 [-1.2086205952162425 -1.1852632900730093 'Indore' 'Male' 1]
 [-0.22533604317590963 -0.25564502334908046 'Indore' 'Male' 3]
 [0.26630623284425686 0.3641004878002055 'Mumbai' 'Male' 5]
 [-0.7169783191960761 -0.8753905344983663 'Delhi' 'Female' 2]
 [1.085710026211201 0.9838459989494914 'Indore' 'Male' 8]
 [-0.06145528450252081 0.05422773222556252 'Bhopal' 'Female' 4]
 [1.9051138195781452 1.9134642656734204 'Mumbai' 'Male' 10]]