<a href="https://colab.research.google.com/github/amitsingh6261/Machine_learning/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import pandas as pd



data = {
    "Age": [21, 25, 19, 32, 28, 24, 35, 22, 29, 31,
            20, 27, 38, 23, 41, 26, 30, 34, 18, 36,
            27, 33, 45, 24, 39],

    "Gender": ["Male", "Female", "Male", "Female", "Male",
               "Female", "Male", "Female", "Male", "Female",
               "Male", "Female", "Male", "Female", "Male",
               "Female", "Male", "Female", "Male", "Female",
               "Male", "Female", "Male", "Female", "Male"],

    "Education": ["Graduate", "Postgraduate", "Undergraduate", "Graduate", "Postgraduate",
                  "Graduate", "Graduate", "Undergraduate", "Postgraduate", "Graduate",
                  "Undergraduate", "Graduate", "Postgraduate", "Undergraduate", "Graduate",
                  "Postgraduate", "Graduate", "Graduate", "Undergraduate", "Postgraduate",
                  "Graduate", "Graduate", "Postgraduate", "Undergraduate", "Graduate"],

"Review": ["Good", "Excellent", "Average", "Good", "Excellent",
               "Poor", "Good", "Average", "Good", "Excellent",
               "Poor", "Good", "Excellent", "Average", "Good",
               "Excellent", "Average", "Good", "Poor", "Excellent",
               "Good", "Average", "Excellent", "Poor", "Good"],

    "Purchased": ["Yes", "Yes", "No", "Yes", "Yes",
                  "No", "Yes", "No", "Yes", "Yes",
                  "No", "Yes", "Yes", "No", "Yes",
                  "Yes", "No", "Yes", "No", "Yes",
                  "Yes", "No", "Yes", "No", "Yes"],


}

df = pd.DataFrame(data)

print(df)

    Age  Gender      Education     Review Purchased
0    21    Male       Graduate       Good       Yes
1    25  Female   Postgraduate  Excellent       Yes
2    19    Male  Undergraduate    Average        No
3    32  Female       Graduate       Good       Yes
4    28    Male   Postgraduate  Excellent       Yes
5    24  Female       Graduate       Poor        No
6    35    Male       Graduate       Good       Yes
7    22  Female  Undergraduate    Average        No
8    29    Male   Postgraduate       Good       Yes
9    31  Female       Graduate  Excellent       Yes
10   20    Male  Undergraduate       Poor        No
11   27  Female       Graduate       Good       Yes
12   38    Male   Postgraduate  Excellent       Yes
13   23  Female  Undergraduate    Average        No
14   41    Male       Graduate       Good       Yes
15   26  Female   Postgraduate  Excellent       Yes
16   30    Male       Graduate    Average        No
17   34  Female       Graduate       Good       Yes
18   18    Male  Undergraduate       Poor        No
19   36  Female   Postgraduate  Excellent       Yes
20   27    Male       Graduate       Good       Yes
21   33  Female       Graduate    Average        No
22   45    Male   Postgraduate  Excellent       Yes
23   24  Female  Undergraduate       Poor        No
24   39    Male       Graduate       Good       Yes

In [62]:
df=df.iloc[:,2:]

In [63]:
df

        Education     Review Purchased
0        Graduate       Good       Yes
1    Postgraduate  Excellent       Yes
2   Undergraduate    Average        No
3        Graduate       Good       Yes
4    Postgraduate  Excellent       Yes
5        Graduate       Poor        No
6        Graduate       Good       Yes
7   Undergraduate    Average        No
8    Postgraduate       Good       Yes
9        Graduate  Excellent       Yes
10  Undergraduate       Poor        No
11       Graduate       Good       Yes
12   Postgraduate  Excellent       Yes
13  Undergraduate    Average        No
14       Graduate       Good       Yes
15   Postgraduate  Excellent       Yes
16       Graduate    Average        No
17       Graduate       Good       Yes
18  Undergraduate       Poor        No
19   Postgraduate  Excellent       Yes
20       Graduate       Good       Yes
21       Graduate    Average        No
22   Postgraduate  Excellent       Yes
23  Undergraduate       Poor        No
24       Graduate       Good       Yes

In [64]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [65]:
x_train

        Education     Review
7   Undergraduate    Average
12   Postgraduate  Excellent
0        Graduate       Good
11       Graduate       Good
21       Graduate    Average
6        Graduate       Good
24       Graduate       Good
10  Undergraduate       Poor
19   Postgraduate  Excellent
23  Undergraduate       Poor
14       Graduate       Good
4    Postgraduate  Excellent
3        Graduate       Good
20       Graduate       Good
5        Graduate       Poor
2   Undergraduate    Average
15   Postgraduate  Excellent
13  Undergraduate    Average
16       Graduate    Average
8    Postgraduate       Good

In [66]:
x_test

        Education     Review
22   Postgraduate  Excellent
18  Undergraduate       Poor
9        Graduate  Excellent
1    Postgraduate  Excellent
17       Graduate       Good

In [67]:
from sklearn.preprocessing import OrdinalEncoder

ordinal = OrdinalEncoder(
    categories=[
        ['Undergraduate', 'Graduate', 'Postgraduate'],
        ['Poor', 'Average', 'Good', 'Excellent']
    ]
)

ordinal.fit(x_train)

OrdinalEncoder(categories=[['Undergraduate', 'Graduate', 'Postgraduate'],
                           ['Poor', 'Average', 'Good', 'Excellent']])

In [68]:
x_train=ordinal.transform(x_train)

In [69]:
x_train

array([[0., 1.],
       [2., 3.],
       [1., 2.],
       [1., 2.],
       [1., 1.],
       [1., 2.],
       [1., 2.],
       [0., 0.],
       [2., 3.],
       [0., 0.],
       [1., 2.],
       [2., 3.],
       [1., 2.],
       [1., 2.],
       [1., 0.],
       [0., 1.],
       [2., 3.],
       [0., 1.],
       [1., 1.],
       [2., 2.]])

In [70]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [71]:
le.fit(y_train)

LabelEncoder()

In [72]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [73]:
y_train=le.transform(y_train)
y_train=le.transform(y_test)

In [74]:
y_train

array([1, 0, 1, 1, 1])